apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: docker-deploy
labels: creationTimestamp
objects:
  kind: Route
  metadata:
    annatotions:
      haproxy.router.openshift.io/timeout: ${SERVER_TIMEOUT}
    labels:
      app: ${APP_NAME}
      name: ${APP_NAME}  
